/**
 * socket.js — Pure relay. The server NEVER sees plaintext.
 * It only forwards opaque encrypted payloads between connected clients.
 */
module.exports = (io) => {
  // userId → socketId mapping (in-memory, ephemeral)
  const onlineUsers = new Map();

  io.on('connection', (socket) => {
    console.log(` Socket connected: ${socket.id}`);

    // ── Register ────────────────────────────────────────────────────────────
    // Client sends their userId after connecting so we can route messages.
    socket.on('register', ({ userId }) => {
      if (!userId) return;
      onlineUsers.set(userId, socket.id);
      socket.userId = userId;
      console.log(`  Registered: ${userId}`);

      // Notify the client of their own socket assignment (useful for debugging)
      socket.emit('registered', { success: true, socketId: socket.id });
    });

    // ── Typing indicator ────────────────────────────────────────────────────
    socket.on('typing', ({ to, isTyping }) => {
      const recipientSocketId = onlineUsers.get(to);
      if (recipientSocketId) {
        io.to(recipientSocketId).emit('typing', {
          from: socket.userId,
          isTyping,
        });
      }
    });

    // ── Send encrypted text message ─────────────────────────────────────────
    // payload = { ciphertext, nonce, mac } — base64 strings — server never decrypts
    socket.on('send_message', ({ to, payload, messageId }) => {
      const recipientSocketId = onlineUsers.get(to);
      if (recipientSocketId) {
        io.to(recipientSocketId).emit('receive_message', {
          from: socket.userId,
          payload,         // opaque encrypted blob
          messageId,       // UUID generated by sender
          sentAt: Date.now(),
        });
      }
      // If recipient is offline → message is dropped (ephemeral by design).
      // Optionally: queue in MongoDB with a TTL index for offline delivery.
    });

    // ── Send encrypted media metadata ───────────────────────────────────────
    // payload = encrypted JSON containing { downloadUrl, nonce, mac, originalExt }
    socket.on('send_media', ({ to, payload, messageId }) => {
      const recipientSocketId = onlineUsers.get(to);
      if (recipientSocketId) {
        io.to(recipientSocketId).emit('receive_media', {
          from: socket.userId,
          payload,
          messageId,
          sentAt: Date.now(),
        });
      }
    });

    // ── Message delivery acknowledgement ────────────────────────────────────
    socket.on('message_ack', ({ to, messageId }) => {
      const recipientSocketId = onlineUsers.get(to);
      if (recipientSocketId) {
        io.to(recipientSocketId).emit('message_ack', { messageId });
      }
    });

    // ── Disconnect ──────────────────────────────────────────────────────────
    socket.on('disconnect', () => {
      if (socket.userId) {
        onlineUsers.delete(socket.userId);
        console.log(`  Disconnected: ${socket.userId}`);
      }
    });
  });
};
