// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmi9watS1x3lrQLt3l0x6r2K2-8AXt4WQ',
    appId: '1:251505035498:web:12a10beef3c3e0b53daf93',
    messagingSenderId: '251505035498',
    projectId: 'chatapp-b46ea',
    authDomain: 'chatapp-b46ea.firebaseapp.com',
    storageBucket: 'chatapp-b46ea.firebasestorage.app',
    measurementId: 'G-TMF6K5V6CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAD33NcZ0oqOXdUVetJwx1ReEtn2kkFzk',
    appId: '1:251505035498:android:e74b4fa78747f9433daf93',
    messagingSenderId: '251505035498',
    projectId: 'chatapp-b46ea',
    storageBucket: 'chatapp-b46ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Z1XeKb1QmYDo83Rh3_w25HovugP6_7g',
    appId: '1:251505035498:ios:a8529f43747b1b5e3daf93',
    messagingSenderId: '251505035498',
    projectId: 'chatapp-b46ea',
    storageBucket: 'chatapp-b46ea.firebasestorage.app',
    iosBundleId: 'com.example.securechat',
  );
}
